Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 20, in _parse
    return parser(tokens)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/grammator.py", line 695, in parse
    return parser.parse(iter(tokens))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/parser.py", line 168, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token COLON here:

   1 def conv(n):
   2     ls=["","uno", "due", "tre", "quattro", "cinque", "sei", "sette", "otto", "nove", "dieci", "undici", "dodici", "tredici", "quattordici", "quindici", "sedici", "diciassette", "diciotto", "diciannove"]
   3     decine=["venti", "trenta", "quaranta","cinquanta", "sessanta", "settanta", "ottanta", "novanta"]
   4     decine1=["vent", "trent", "quarant","cinquant", "sessant", "settant", "ottant", "novant"]
   5     centinaia:<---- here

The token COLON should be one of those: AMPER_EQUAL, CIRCUMFLEX_EQUAL, COMMENT, DOUBLE_SLASH_EQUAL, DOUBLE_STAR_EQUAL, ENDL, EQUAL, LEFT_SHIFT_EQUAL, MINUS_EQUAL, PERCENT_EQUAL, PLUS_EQUAL, RIGHT_SHIFT_EQUAL, SEMICOLON, SLASH_EQUAL, STAR_EQUAL, VBAR_EQUAL

It is not normal that you see this error, it means that Baron has failed to parse valid Python code. It would be kind if you can extract the snippet of your code that makes Baron fail and open a bug here: https://github.com/Psycojoker/baron/issues

Sorry for the inconvenience.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/cc.py", line 84, in <module>
    results=cc.evaluate(file)
  File "lib/cc.py", line 19, in evaluate
    red = redbaron.RedBaron(file.read())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/redbaron/redbaron.py", line 36, in __init__
    self.node_list = base_nodes.NodeList.from_fst(baron.parse(source_code), parent=self, on_attribute="root")
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 66, in parse
    return _parse(tokens, print_function)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 26, in _parse
    raise e
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/baron.py", line 24, in _parse
    return parser(tokens)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/grammator.py", line 695, in parse
    return parser.parse(iter(tokens))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/baron/parser.py", line 168, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token COLON here:

   1 def conv(n):
   2     ls=["","uno", "due", "tre", "quattro", "cinque", "sei", "sette", "otto", "nove", "dieci", "undici", "dodici", "tredici", "quattordici", "quindici", "sedici", "diciassette", "diciotto", "diciannove"]
   3     decine=["venti", "trenta", "quaranta","cinquanta", "sessanta", "settanta", "ottanta", "novanta"]
   4     decine1=["vent", "trent", "quarant","cinquant", "sessant", "settant", "ottant", "novant"]
   5     centinaia:<---- here

The token COLON should be one of those: AMPER_EQUAL, CIRCUMFLEX_EQUAL, COMMENT, DOUBLE_SLASH_EQUAL, DOUBLE_STAR_EQUAL, ENDL, EQUAL, LEFT_SHIFT_EQUAL, MINUS_EQUAL, PERCENT_EQUAL, PLUS_EQUAL, RIGHT_SHIFT_EQUAL, SEMICOLON, SLASH_EQUAL, STAR_EQUAL, VBAR_EQUAL

It is not normal that you see this error, it means that Baron has failed to parse valid Python code. It would be kind if you can extract the snippet of your code that makes Baron fail and open a bug here: https://github.com/Psycojoker/baron/issues

Sorry for the inconvenience.
