============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.7.0, py-1.5.2, pluggy-0.7.1 -- /home/travis/virtualenv/python3.6.3/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/Fondamenti18/fondamenti-di-programmazione/students/1817406/homework01, inifile:
plugins: timeout-1.3.1, json-0.4.0
timeout: 10.0s
timeout method: signal
timeout func_only: False
collecting ... collected 0 items / 1 errors

==================================== ERRORS ====================================
_________________________ ERROR collecting grade02.py __________________________
grade02.py:6: in <module>
    import program02 as program
program02.py:57: in <module>
    numero_1=numero#per avere il numero originale
E   NameError: name 'numero' is not defined
 generated json report: /home/travis/build/Fondamenti18/fondamenti-di-programmazione/students/1817406/homework01/program02.log.json 
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.21 seconds ============================
